command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: DASHBOARD_URL
    value: "https://dbc-1e27e56a-90cd.cloud.databricks.com/embed/dashboardsv3/01f1271698161d42b3c66528415775e8?o=1048934788948873"
  - name: MULTI_PAGE_DASHBOARD_URL
    value: "https://dbc-1e27e56a-90cd.cloud.databricks.com/embed/dashboardsv3/01f1271698161d42b3c66528415775e8?o=1048934788948873"
  - name: GENIE_SPACE_ID
    value: "01f127092d2219f3be10180d79b2ee5d"
  - name: WAREHOUSE_ID
    value: "c82e264eefa2d2f5"
  - name: MAS_ENDPOINT
    value: "https://dbc-1e27e56a-90cd.cloud.databricks.com/serving-endpoints/mas-d4bc5d36-endpoint/invocations"

resources:
  - name: genie-space
    genie_space:
      space_id: "01f127092d2219f3be10180d79b2ee5d"
      permission: CAN_RUN
  - name: sql-warehouse
    sql_warehouse:
      id: "c82e264eefa2d2f5"
      permission: CAN_USE
  - name: serving-endpoint
    serving_endpoint:
      name: "mas-d4bc5d36-endpoint"
      permission: CAN_QUERY

user_api_scopes:
  - sql
